name: build_windows

on:
  pull_request:
  push:

env:
  BRANCH: ${{ github.base_ref || github.ref_name }}

jobs:
  build_lld:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
    name: Build LLD ${{ matrix.arch }}
    runs-on: windows-2022
    timeout-minutes: 120
    env:
      VSINSTALLDIR: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\
      # NB: update windows/build_lld.sha256sums as well
      LLVM_VER: 9.0.0
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - shell: cmd
        run: call windows\build_lld.bat || exit /b
      - uses: actions/upload-artifact@v4
        with:
          name: lld-${{ matrix.arch }}
          path: artifacts/

  build_mingw_libs:
    name: Build MinGW-based libs
    runs-on: windows-2022
    timeout-minutes: 120
    env:
      VSINSTALLDIR: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\
      # NB: update windows/build_mingw.sha256sums as well
      MINGW_VER: 8.0.0
      D_VERSION: 2.077.1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - shell: cmd
        run: call windows\build_mingw.bat || exit /b
      - uses: actions/upload-artifact@v4
        with:
          name: mingw-libs
          path: artifacts/

  build_curl:
    name: Build curl
    runs-on: windows-2022
    timeout-minutes: 120
    env:
      VSINSTALLDIR: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\
      # NB: update windows/build_curl.sha256sums as well
      CURL_VER: 7.68.0
      ZLIB_VER: 1.2.11
      PEXPORTS_VER: 0.47
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - shell: cmd
        run: call windows\build_curl.bat || exit /b
      - uses: actions/upload-artifact@v4
        with:
          name: curl
          path: artifacts/
